name: EventuallyURL
author: Timothy Stiles
description: adds the URL of the triggered event's payload to GITHUB.EVENT_URL.
outputs:
  errorMessage:
    description: 'This action failed to run.'
  sentMessage:
    description: 'the env.EVENT_URL is {{env.EVENT_URL}}'
runs:
  using: docker
  image: Dockerfile
#  using: docker
#  image: docker://ghcr.io/the-gophers/go-action:1.0.0
